#!/usr/bin/env python3
"""Send a synthetic or real-ANPR passage through the campus control plane."""

from __future__ import annotations

import argparse
import json
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import cast

from number_plate_recognition.adapters.ultralytics import load_model_bundle
from number_plate_recognition.config import AppConfig
from number_plate_recognition.domain import PlateResult
from number_plate_recognition.imaging import decode_image
from number_plate_recognition.pipeline import RecognitionPipeline

type JsonScalar = bool | int | float | str | None
type JsonValue = JsonScalar | list[JsonValue] | dict[str, JsonValue]

_EVIDENCE_LABEL = "Synthetic composite - generated by scripts/simulate_gate.py"


class ApiError(RuntimeError):
    """Raised when the local control plane rejects a simulator request."""


@dataclass(frozen=True, slots=True)
class ApiClient:
    """Tiny same-purpose HTTP client with explicit demo identity boundaries."""

    base_url: str
    organization_id: str

    def request(
        self,
        method: str,
        path: str,
        *,
        token: str,
        payload: dict[str, JsonValue] | None = None,
    ) -> JsonValue:
        body = None if payload is None else json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(  # noqa: S310 - operator supplies the local API URL
            f"{self.base_url.rstrip('/')}{path}",
            data=body,
            method=method,
            headers={
                "Accept": "application/json",
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
                "X-Organization-ID": self.organization_id,
            },
        )
        try:
            with urllib.request.urlopen(request, timeout=10) as response:  # noqa: S310
                raw = response.read(1_000_000)
        except urllib.error.HTTPError as exc:
            detail = exc.read(16_384).decode("utf-8", errors="replace")
            raise ApiError(f"{method} {path} returned HTTP {exc.code}: {detail}") from exc
        except urllib.error.URLError as exc:
            raise ApiError(f"Cannot reach the control plane at {self.base_url}") from exc
        if not raw:
            return None
        return cast(JsonValue, json.loads(raw))


@dataclass(frozen=True, slots=True)
class RecognitionInput:
    plate_text: str | None
    detection_confidence: float | None
    recognition_confidence: float | None
    format_valid: bool
    model_version: str
    status: str


def _recognition_from_plate(
    plate_text: str | None,
    *,
    confidence: float,
    format_valid: bool,
) -> RecognitionInput:
    normalized = plate_text.strip().upper() if plate_text else None
    return RecognitionInput(
        plate_text=normalized,
        detection_confidence=confidence if normalized else None,
        recognition_confidence=confidence if normalized else None,
        format_valid=format_valid and bool(normalized),
        model_version="simulator@v1",
        status="recognized" if normalized and format_valid else "uncertain",
    )


def _recognition_from_image(path: Path) -> RecognitionInput:
    config = AppConfig.from_env()
    payload = path.read_bytes()
    image = decode_image(
        payload,
        max_bytes=config.max_upload_bytes,
        max_pixels=config.max_image_pixels,
    )
    result = RecognitionPipeline(load_model_bundle(config), config).process(image)
    best: PlateResult | None = max(
        result.plates,
        key=lambda plate: plate.recognition_confidence,
        default=None,
    )
    versions = "/".join(
        f"{name}:{version}" for name, version in sorted(result.model_versions.items())
    )
    if best is None:
        return RecognitionInput(
            plate_text=None,
            detection_confidence=None,
            recognition_confidence=None,
            format_valid=False,
            model_version=versions or "unknown",
            status="unreadable",
        )
    return RecognitionInput(
        plate_text=best.text or None,
        detection_confidence=best.detection_confidence,
        recognition_confidence=best.recognition_confidence,
        format_valid=best.format_valid,
        model_version=versions or "unknown",
        status="recognized" if best.text and best.format_valid else "uncertain",
    )


def _object(value: JsonValue, *, context: str) -> dict[str, JsonValue]:
    if not isinstance(value, dict):
        raise ApiError(f"{context} returned an unexpected response")
    return value


def _objects(value: JsonValue, *, context: str) -> list[dict[str, JsonValue]]:
    if not isinstance(value, list) or any(not isinstance(item, dict) for item in value):
        raise ApiError(f"{context} returned an unexpected response")
    return cast(list[dict[str, JsonValue]], value)


def _canonical_plate(value: JsonValue) -> str:
    return "".join(character for character in str(value or "").upper() if character.isalnum())


def _policy_decision(
    recognition: RecognitionInput,
    grants: list[dict[str, JsonValue]],
    *,
    gate_id: str,
    confidence_threshold: float,
) -> dict[str, JsonValue]:
    confidence = recognition.recognition_confidence or 0.0
    if (
        not recognition.plate_text
        or not recognition.format_valid
        or confidence < confidence_threshold
    ):
        return {
            "outcome": "review_required",
            "reason": "Recognition was missing, invalid, or below the automatic-decision threshold.",
            "source": "policy",
        }

    target = _canonical_plate(recognition.plate_text)
    matches = [grant for grant in grants if _canonical_plate(grant.get("plate_text")) == target]
    revoked = next((grant for grant in matches if grant.get("status") == "revoked"), None)
    if revoked is not None:
        return {
            "outcome": "denied",
            "reason": "A matching access grant has been revoked.",
            "source": "policy",
            "grant_id": revoked["id"],
        }
    active = next((grant for grant in matches if grant.get("status") == "active"), None)
    if active is None:
        return {
            "outcome": "no_match",
            "reason": "No active digital access grant matches the recognized plate.",
            "source": "policy",
        }
    allowed_gate = active.get("gate_id")
    if isinstance(allowed_gate, str) and allowed_gate != gate_id:
        return {
            "outcome": "review_required",
            "reason": f"The grant is valid at a different gate ({allowed_gate}); redirect required.",
            "source": "policy",
            "grant_id": active["id"],
        }
    return {
        "outcome": "allowed",
        "reason": "Exact plate match against an active digital access grant.",
        "source": "policy",
        "grant_id": active["id"],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-url", default="http://127.0.0.1:8000")
    parser.add_argument("--organization", default="org-atlas")
    parser.add_argument("--site", default="site-atlas-main")
    parser.add_argument("--gate", default="gate-atlas-north")
    parser.add_argument("--camera", default="camera-atlas-north-anpr")
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--image", type=Path, help="run the real local ANPR models")
    source.add_argument("--plate", default="12345-A-6", help="use a synthetic recognition")
    parser.add_argument("--confidence", type=float, default=0.94)
    parser.add_argument("--threshold", type=float, default=0.80)
    parser.add_argument("--invalid-format", action="store_true")
    parser.add_argument("--no-decision", action="store_true")
    parser.add_argument("--edge-token", default="demo-edge")
    parser.add_argument("--decision-token", default="demo-admin")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    if not 0.0 <= arguments.confidence <= 1.0:
        raise SystemExit("--confidence must be between 0 and 1")
    if not 0.0 <= arguments.threshold <= 1.0:
        raise SystemExit("--threshold must be between 0 and 1")

    occurred_at = datetime.now(UTC).isoformat()
    try:
        recognition = (
            _recognition_from_image(arguments.image)
            if arguments.image is not None
            else _recognition_from_plate(
                arguments.plate,
                confidence=arguments.confidence,
                format_valid=not arguments.invalid_format,
            )
        )
        client = ApiClient(arguments.api_url, arguments.organization)
        passage = _object(
            client.request(
                "POST",
                "/api/v1/passages",
                token=arguments.edge_token,
                payload={
                    "site_id": arguments.site,
                    "gate_id": arguments.gate,
                    "camera_id": arguments.camera,
                    "direction": "inbound",
                    "occurred_at": occurred_at,
                    "evidence_label": _EVIDENCE_LABEL,
                },
            ),
            context="passage creation",
        )
        passage_id = str(passage["id"])
        recognition_record = _object(
            client.request(
                "POST",
                f"/api/v1/passages/{urllib.parse.quote(passage_id)}/recognitions",
                token=arguments.edge_token,
                payload={
                    "status": recognition.status,
                    "plate_text": recognition.plate_text,
                    "detection_confidence": recognition.detection_confidence,
                    "recognition_confidence": recognition.recognition_confidence,
                    "format_valid": recognition.format_valid,
                    "model_version": recognition.model_version,
                    "source": "central_worker" if arguments.image else "gate_simulator",
                    "evidence_label": _EVIDENCE_LABEL,
                },
            ),
            context="recognition ingestion",
        )
        decision_record: JsonValue = None
        final_passage = passage
        if not arguments.no_decision:
            grants = _objects(
                client.request(
                    "GET",
                    "/api/v1/access-grants",
                    token=arguments.decision_token,
                ),
                context="grant lookup",
            )
            decision = _policy_decision(
                recognition,
                grants,
                gate_id=arguments.gate,
                confidence_threshold=arguments.threshold,
            )
            decision_record = client.request(
                "POST",
                f"/api/v1/passages/{urllib.parse.quote(passage_id)}/authorization-decisions",
                token=arguments.decision_token,
                payload=decision,
            )
            final_passage = _object(
                client.request(
                    "GET",
                    f"/api/v1/passages/{urllib.parse.quote(passage_id)}",
                    token=arguments.decision_token,
                ),
                context="final passage read",
            )
    except (ApiError, OSError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    print(
        json.dumps(
            {
                "passage": final_passage,
                "recognition": recognition_record,
                "authorization_decision": decision_record,
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
