/**
 * Deterministic demonstration snapshot. IDs and values intentionally remain
 * stable so screenshots, interviews, and UI tests are reproducible.
 */
export const DEMO_DATA = Object.freeze({
  meta: {
    generatedAt: "2026-08-21T09:42:00+01:00",
    campusName: "Ben Guerir Campus",
    weather: { en: "31°C · Clear", fr: "31°C · Ciel dégagé", ar: "31°C · صحو" },
    shift: "Morning shift",
  },
  gates: [
    {
      id: "gate-main",
      code: "G01",
      name: { en: "Main Gate", fr: "Entrée principale", ar: "البوابة الرئيسية" },
      zone: { en: "Academic core", fr: "Pôle académique", ar: "القطب الأكاديمي" },
      status: "open",
      x: 20,
      y: 71,
      lanes: 3,
      queue: 4,
      waitMinutes: 2,
      throughput: 184,
      cameraHealth: 100,
      operator: "Salma E.",
      plate: "12345 · أ · 26",
      confidence: 98.7,
    },
    {
      id: "gate-innovation",
      code: "G02",
      name: { en: "Innovation Gate", fr: "Entrée Innovation", ar: "بوابة الابتكار" },
      zone: { en: "StartGate & labs", fr: "StartGate et laboratoires", ar: "ستارت غيت والمختبرات" },
      status: "open",
      x: 75,
      y: 22,
      lanes: 2,
      queue: 1,
      waitMinutes: 1,
      throughput: 112,
      cameraHealth: 100,
      operator: "Youssef K.",
      plate: "48217 · ب · 17",
      confidence: 96.4,
    },
    {
      id: "gate-residential",
      code: "G03",
      name: { en: "Residential Gate", fr: "Entrée Résidences", ar: "بوابة الإقامات" },
      zone: { en: "Student residences", fr: "Résidences étudiantes", ar: "الإقامات الطلابية" },
      status: "degraded",
      x: 76,
      y: 72,
      lanes: 2,
      queue: 7,
      waitMinutes: 5,
      throughput: 76,
      cameraHealth: 67,
      operator: "Imane B.",
      plate: "76103 · د · 10",
      confidence: 91.2,
    },
    {
      id: "gate-logistics",
      code: "G04",
      name: { en: "Logistics Gate", fr: "Entrée Logistique", ar: "بوابة الخدمات اللوجستية" },
      zone: { en: "Deliveries & services", fr: "Livraisons et services", ar: "التوصيل والخدمات" },
      status: "maintenance",
      x: 15,
      y: 22,
      lanes: 1,
      queue: 0,
      waitMinutes: 0,
      throughput: 24,
      cameraHealth: 50,
      operator: "Maintenance",
      plate: "—",
      confidence: 0,
    },
  ],
  arrivals: [
    {
      id: "arr-1048",
      gateId: "gate-main",
      plate: "12345 · أ · 26",
      person: "Nadia El Mansouri",
      organization: "Research Institute",
      purpose: "Staff arrival",
      decision: "approved",
      confidence: 98.7,
      minutesAgo: 0,
      color: "Graphite SUV",
      avatar: "NM",
    },
    {
      id: "arr-1047",
      gateId: "gate-residential",
      plate: "76103 · د · 10",
      person: "Omar Benali",
      organization: "Student residence R4",
      purpose: "Resident access",
      decision: "review",
      confidence: 91.2,
      minutesAgo: 2,
      color: "White hatchback",
      avatar: "OB",
    },
    {
      id: "arr-1046",
      gateId: "gate-innovation",
      plate: "48217 · ب · 17",
      person: "Claire Dubois",
      organization: "GreenTech Partners",
      purpose: "Scheduled visitor",
      decision: "approved",
      confidence: 96.4,
      minutesAgo: 4,
      color: "Silver sedan",
      avatar: "CD",
    },
    {
      id: "arr-1045",
      gateId: "gate-main",
      plate: "33591 · و · 6",
      person: { en: "Unmatched vehicle", fr: "Véhicule non reconnu", ar: "مركبة غير مطابقة" },
      organization: "No active invitation",
      purpose: "Manual verification",
      decision: "denied",
      confidence: 99.1,
      minutesAgo: 7,
      color: "Blue van",
      avatar: "?",
    },
    {
      id: "arr-1044",
      gateId: "gate-main",
      plate: "94820 · هـ · 26",
      person: "Mehdi Alaoui",
      organization: "Campus services",
      purpose: "Fleet access",
      decision: "approved",
      confidence: 97.8,
      minutesAgo: 11,
      color: "White utility",
      avatar: "MA",
    },
  ],
  requests: [
    {
      id: "REQ-2381",
      person: "Omar Benali",
      plate: "76103 · د · 10",
      host: "Residence R4",
      window: "Today · 08:00–23:00",
      reason: "Resident vehicle replacement",
      risk: "medium",
      status: "pending",
      submittedMinutes: 8,
    },
    {
      id: "REQ-2380",
      person: "Sofia Marquez",
      plate: "1549 · Espagne",
      host: "Africa Business School",
      window: "Today · 10:00–17:00",
      reason: "Guest lecturer",
      risk: "low",
      status: "pending",
      submittedMinutes: 21,
    },
    {
      id: "REQ-2379",
      person: "Atlas Facilities",
      plate: "64122 · ج · 1",
      host: "Estates team",
      window: "24–26 Aug · 06:00–18:00",
      reason: "Cooling plant maintenance",
      risk: "low",
      status: "approved",
      submittedMinutes: 54,
    },
  ],
  directory: [
    {
      id: "P-1024",
      kind: "person",
      name: "Nadia El Mansouri",
      organization: "Research Institute",
      email: "n.elmansouri@example.ma",
      status: "active",
      access: "Staff · All weekdays",
      initials: "NM",
    },
    {
      id: "P-1008",
      kind: "person",
      name: "Omar Benali",
      organization: "Student · Residence R4",
      email: "o.benali@example.ma",
      status: "review",
      access: "Resident · 06:00–00:00",
      initials: "OB",
    },
    {
      id: "P-1162",
      kind: "person",
      name: "Claire Dubois",
      organization: "GreenTech Partners",
      email: "claire.d@example.com",
      status: "visitor",
      access: "Visitor · Today only",
      initials: "CD",
    },
    {
      id: "V-3021",
      kind: "vehicle",
      name: "Nadia's vehicle",
      plate: "12345 · أ · 26",
      organization: "Research Institute",
      status: "active",
      access: "Linked to P-1024",
      initials: "26",
    },
    {
      id: "V-3098",
      kind: "vehicle",
      name: "Campus fleet 14",
      plate: "94820 · هـ · 26",
      organization: "Campus services",
      status: "active",
      access: "Fleet · Service gates",
      initials: "14",
    },
    {
      id: "V-3104",
      kind: "vehicle",
      name: "Unmatched vehicle",
      plate: "33591 · و · 6",
      organization: "Unknown",
      status: "blocked",
      access: "Manual review required",
      initials: "?",
    },
  ],
  incidents: [
    {
      id: "INC-0412",
      severity: "high",
      title: "Tailgating signal",
      description: "Two vehicles crossed on one approval at Residential Gate.",
      gateId: "gate-residential",
      status: "investigating",
      owner: "Security desk",
      minutesAgo: 6,
    },
    {
      id: "INC-0411",
      severity: "medium",
      title: "Camera 2 intermittent",
      description: "Plate camera dropped 18% of frames during the last 10 minutes.",
      gateId: "gate-residential",
      status: "assigned",
      owner: "IT operations",
      minutesAgo: 18,
    },
    {
      id: "INC-0410",
      severity: "low",
      title: "Planned lane maintenance",
      description: "Logistics lane closed for barrier sensor calibration.",
      gateId: "gate-logistics",
      status: "monitoring",
      owner: "Facilities",
      minutesAgo: 43,
    },
  ],
  devices: [
    { id: "CAM-G01-A", gateId: "gate-main", type: "Plate camera", status: "online", latency: 42, uptime: 99.99 },
    { id: "BAR-G01-A", gateId: "gate-main", type: "Barrier", status: "online", latency: 18, uptime: 99.98 },
    { id: "CAM-G02-A", gateId: "gate-innovation", type: "Plate camera", status: "online", latency: 48, uptime: 99.96 },
    { id: "INT-G02-A", gateId: "gate-innovation", type: "Intercom", status: "online", latency: 61, uptime: 99.91 },
    { id: "CAM-G03-B", gateId: "gate-residential", type: "Context camera", status: "degraded", latency: 284, uptime: 97.42 },
    { id: "BAR-G03-A", gateId: "gate-residential", type: "Barrier", status: "online", latency: 31, uptime: 99.94 },
    { id: "CAM-G04-A", gateId: "gate-logistics", type: "Plate camera", status: "maintenance", latency: 0, uptime: 96.88 },
    { id: "SEN-G04-A", gateId: "gate-logistics", type: "Loop sensor", status: "maintenance", latency: 0, uptime: 98.12 },
  ],
  analytics: {
    totalEntries: 1284,
    approvalRate: 94.6,
    medianDecisionSeconds: 3.8,
    peakHour: "08:00–09:00",
    hourly: [24, 31, 58, 92, 126, 151, 138, 119, 104, 132, 91, 66],
    days: [
      { label: "Mon", value: 1138 },
      { label: "Tue", value: 1264 },
      { label: "Wed", value: 1192 },
      { label: "Thu", value: 1347 },
      { label: "Fri", value: 1284 },
      { label: "Sat", value: 672 },
      { label: "Sun", value: 488 },
    ],
    decisions: { approved: 94.6, review: 3.2, denied: 2.2 },
    gateTraffic: [
      { gateId: "gate-main", value: 46 },
      { gateId: "gate-innovation", value: 29 },
      { gateId: "gate-residential", value: 19 },
      { gateId: "gate-logistics", value: 6 },
    ],
  },
});
